const colors = require('tailwindcss/colors')

module.exports = {
    theme: {
        borderRadius: {
            'none': '0',
            'sm': '0.125rem',
            DEFAULT: '0.25rem',
            'md': '0.375rem',
            'lg': '0.5rem',
            'full': '9999px',
            'large': '12px',
            '2xl': '1rem',
        },
        colors: {
            transparent: 'transparent',
            current: 'currentColor',
            black: colors.black,
            white: colors.white,
            gray: colors.gray,
            emerald: colors.emerald,
            indigo: colors.indigo,
            yellow: colors.yellow,
            primary: '#006FFD',
            'primary-focus': '#005CE6',
            'primary-content': '#FFFFFF',
            secondary: '#6B4CFF',
            'secondary-focus': '#5232E6',
            'secondary-content': '#FFFFFF',
            accent: '#FF6B4C',
            'accent-focus': '#E65232',
            'accent-content': '#FFFFFF',
            neutral: '#F2F2F2',
            'neutral-focus': '#E6E6E6',
            'neutral-content': '#333333',
            'base-100': '#FFFFFF',
            'base-200': '#F9FAFB',
            'base-300': '#F2F2F2',
            'base-content': '#333333',
            info: '#00B5FF',
            success: '#28A745',
            warning: '#FFC107',
            error: '#DC3545',
        },
    },
    plugins: [],
}
